Name: Prashant Pakuwal
ID: 2357806


Task: 1

In [ ]:
def convert_length(value, unit):
    """
    Converts length between meters and feet.

    Parameters:
    value (float): The numerical value to convert.
    unit (str): The unit of the input value ('m' for meters, 'ft' for feet).

    Returns:
    tuple: Converted value and its unit.
    """
    if unit == 'm':
        return value * 3.28084, 'ft'
    elif unit == 'ft':
        return value / 3.28084, 'm'
    else:
        raise ValueError("Invalid length unit. Choose 'm' or 'ft'.")

def convert_weight(value, unit):
    """
    Converts weight between kilograms and pounds.

    Parameters:
    value (float): The numerical value to convert.
    unit (str): The unit of the input value ('kg' for kilograms, 'lbs' for pounds).

    Returns:
    tuple: Converted value and its unit.
    """
    if unit == 'kg':
        return value * 2.20462, 'lbs'
    elif unit == 'lbs':
        return value / 2.20462, 'kg'
    else:
        raise ValueError("Invalid weight unit. Choose 'kg' or 'lbs'.")

def convert_volume(value, unit):
    """
    Converts volume between liters and gallons.

    Parameters:
    value (float): The numerical value to convert.
    unit (str): The unit of the input value ('L' for liters, 'gal' for gallons).

    Returns:
    tuple: Converted value and its unit.
    """
    if unit == 'L':
        return value * 0.264172, 'gal'
    elif unit == 'gal':
        return value / 0.264172, 'L'
    else:
        raise ValueError("Invalid volume unit. Choose 'L' or 'gal'.")

def main():
    try:
        print("Choose conversion type: \n1. Length \n2. Weight \n3. Volume")
        choice = input("Enter choice (1/2/3): ").strip()

        if choice not in ('1', '2', '3'):
            print("Invalid choice. Please enter 1, 2, or 3.")
            return

        value = float(input("Enter value to convert: ").strip())

        if choice == '1':
            unit = input("Enter unit (m/ft): ").strip().lower()
            result, result_unit = convert_length(value, unit)
        elif choice == '2':
            unit = input("Enter unit (kg/lbs): ").strip().lower()
            result, result_unit = convert_weight(value, unit)
        elif choice == '3':
            unit = input("Enter unit (L/gal): ").strip().lower()
            result, result_unit = convert_volume(value, unit)

        print(f"Converted value: {result:.2f} {result_unit}")

    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"Unexpected error: {e}")

if __name__ == "__main__":
    main()


Choose conversion type: 
1. Length 
2. Weight 
3. Volume
Enter choice (1/2/3): 1
Enter value to convert: 100
Enter unit (m/ft): m
Converted value: 328.08 ft


Task: 2

In [ ]:
def calculate_sum(numbers):
    """
    Returns the sum of a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Returns the average of a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The average of the numbers.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot calculate average of an empty list.")
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    """
    Returns the maximum value from a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The maximum number in the list.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot find maximum of an empty list.")
    return max(numbers)

def find_minimum(numbers):
    """
    Returns the minimum value from a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The minimum number in the list.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot find minimum of an empty list.")
    return min(numbers)

def main():
    try:
        print("Choose an operation: \n1. Sum \n2. Average \n3. Maximum \n4. Minimum")
        choice = input("Enter choice (1/2/3/4): ").strip()

        if choice not in ('1', '2', '3', '4'):
            print("Invalid choice. Please enter 1, 2, 3, or 4.")
            return

        numbers_input = input("Enter a list of numbers separated by spaces: ").strip()
        numbers = [float(num) for num in numbers_input.split()]

        if choice == '1':
            result = calculate_sum(numbers)
        elif choice == '2':
            result = calculate_average(numbers)
        elif choice == '3':
            result = find_maximum(numbers)
        elif choice == '4':
            result = find_minimum(numbers)

        print(f"Result: {result:.2f}")

    except ValueError as e:
        print(f"Error: {e}")
    except Exception as e:
        print(f"Unexpected error: {e}")

if __name__ == "__main__":
    main()


Choose an operation: 
1. Sum 
2. Average 
3. Maximum 
4. Minimum
Enter choice (1/2/3/4): 1
Enter a list of numbers separated by spaces: 10 8
Result: 18.00


4.2 Exercise on List Manipulation:

1. Extract Every Other Element:

In [ ]:
def extract_every_other(lst):
    """
    Extracts every other element from a list, starting from the first element.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list containing every other element from the original list.
    """
    return lst[::2]

example_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(example_list)
print("Extracted elements:", result)


Extracted elements: [1, 3, 5]


2. Slice a Sublist:

In [ ]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from a given list, starting from the specified index and ending at another specified index (inclusive).

    Parameters:
    lst (list): The input list.
    start (int): The starting index.
    end (int): The ending index (inclusive).

    Returns:
    list: A sublist from start to end indices.
    """
    if start < 0 or end >= len(lst) or start > end:
        raise ValueError("Invalid start or end index.")
    return lst[start:end+1]

# Example usage:
example_list = [1, 2, 3, 4, 5, 6]
start_index = 2
end_index = 4
result = get_sublist(example_list, start_index, end_index)
print("Sublist:", result)

Sublist: [3, 4, 5]


3. Reverse a List Using Slicing:

In [ ]:
def reverse_list(lst):
    """
    Reverses a list using slicing.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list with elements in reverse order.
    """
    return lst[::-1]

example_list = [1, 2, 3, 4, 5]
result = reverse_list(example_list)
print("Reversed list:", result)


Reversed list: [5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

In [ ]:
def remove_first_last(lst):
    """
    Removes the first and last elements of a list and returns the resulting sublist.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A sublist without the first and last elements.
    """
    if len(lst) < 2:
        raise ValueError("List must have at least two elements to remove first and last.")
    return lst[1:-1]

example_list = [1, 2, 3, 4, 5]
result = remove_first_last(example_list)
print("Sublist after removing first and last elements:", result)

Sublist after removing first and last elements: [2, 3, 4]


5. Get the First n Elements:

In [ ]:
def get_first_n(lst, n):
    """
    Extracts the first n elements from a list.

    Parameters:
    lst (list): The input list.
    n (int): The number of elements to extract.

    Returns:
    list: A new list containing the first n elements.
    """
    if n < 0:
        raise ValueError("n must be a non-negative integer.")
    return lst[:n]

# Example usage:
example_list = [1, 2, 3, 4, 5]
n = 3
result = get_first_n(example_list, n)
print("First", n, "elements:", result)

First 3 elements: [1, 2, 3]


6. Extract Elements from the End:

In [ ]:
def get_last_n(lst, n):
    """
    Extracts the last n elements from a list.

    Parameters:
    lst (list): The input list.
    n (int): The number of elements to extract from the end.

    Returns:
    list: A new list containing the last n elements.
    """
    if n < 0:
        raise ValueError("n must be a non-negative integer.")
    return lst[-n:] if n else []

example_list = [1, 2, 3, 4, 5]
n = 2
result = get_last_n(example_list, n)
print("Last", n, "elements:", result)

Last 2 elements: [4, 5]


7. Extract Elements in Reverse Order:

In [ ]:
def reverse_skip(lst):
    """
    Extracts elements in reverse order, starting from the second-to-last element and skipping one in between.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list containing every second element from the second-to-last, moving backward.
    """
    return lst[-2::-2]

example_list = [1, 2, 3, 4, 5, 6]
result = reverse_skip(example_list)
print("Extracted elements in reverse order:", result)

Extracted elements in reverse order: [5, 3, 1]


4.3 Exercise on Nested List:

1. Flatten a Nested List:

In [ ]:
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
    lst (list): A nested list containing sublists.

    Returns:
    list: A flattened list with all elements in a single dimension.
    """
    flat_list = []
    for sublist in lst:
        if isinstance(sublist, list):
            flat_list.extend(sublist)
        else:
            flat_list.append(sublist)
    return flat_list

nested_list = [[1, 2], [3, 4], [5]]
result = flatten(nested_list)
print("Flattened list:", result)

Flattened list: [1, 2, 3, 4, 5]


2. Accessing Nested List Elements:

In [ ]:
def access_nested_element(lst, indices):
    """
    Extracts a specific element from a nested list given its indices.

    Parameters:
    lst (list): A nested list.
    indices (list of int): A list of indices to navigate the nested structure.

    Returns:
    any: The element at the specified position.
    """
    element = lst
    for index in indices:
        if not isinstance(element, list) or index >= len(element):
            raise IndexError("Invalid index provided.")
        element = element[index]
    return element

# Example usage:
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(nested_list, indices)
print("Accessed element:", result)

Accessed element: 6


3. Sum of All Elements in a Nested List:

In [ ]:
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list, regardless of depth.

    Parameters:
    lst (list): A nested list containing numbers and/or other lists.

    Returns:
    int/float: The sum of all numerical elements in the nested list.
    """
    total = 0
    for element in lst:
        if isinstance(element, list):
            total += sum_nested(element)  # Recursively sum nested lists
        elif isinstance(element, (int, float)):
            total += element
        else:
            raise ValueError("List contains non-numeric values.")
    return total

nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)
print("Sum of all elements:", result)

Sum of all elements: 21


4. Remove Specific Element from a Nested List:

In [ ]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): A nested list containing elements and/or other lists.
    elem (any): The element to remove from the nested list.

    Returns:
    list: A new nested list with the specified element removed.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            filtered_sublist = remove_element(item, elem)
            if filtered_sublist:  # Only append non-empty lists
                result.append(filtered_sublist)
        elif item != elem:
            result.append(item)
    return result

nested_list = [[1, 2], [3, 2], [4, 5]]
element_to_remove = 2
result = remove_element(nested_list, element_to_remove)
print("Modified nested list:", result)

Modified nested list: [[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:

In [ ]:
def find_max(lst):
    """
    Finds the maximum element in a nested list, regardless of depth.

    Parameters:
    lst (list): A nested list containing numbers and/or other lists.

    Returns:
    int/float: The maximum numerical element in the nested list.
    """
    max_value = float('-inf')

    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, find_max(item))  # Recursively find the max in nested lists
        elif isinstance(item, (int, float)):
            max_value = max(max_value, item)
        else:
            raise ValueError("List contains non-numeric values.")

    if max_value == float('-inf'):
        raise ValueError("List is empty or contains no numeric values.")

    return max_value

nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)
print("Maximum element:", result)

Maximum element: 6


6. Count Occurrences of an Element in a Nested List:

In [ ]:
def count_occurrences(lst, elem):
    """
    Counts the occurrences of a specific element in a nested list.

    Parameters:
    lst (list): A nested list containing elements and/or other lists.
    elem (any): The element to count occurrences of.

    Returns:
    int: The number of times the element appears in the nested list.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)  # Recursively count occurrences in nested lists
        elif item == elem:
            count += 1
    return count

nested_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2
result = count_occurrences(nested_list, element_to_count)
print("Occurrences of", element_to_count, ":", result)


Occurrences of 2 : 3


7. Flatten a List of Lists of Lists:

In [ ]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list, regardless of depth.

    Parameters:
    lst (list): A deeply nested list containing elements and/or other lists.

    Returns:
    list: A flattened list with all elements in a single dimension.
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))  # Recursively flatten nested lists
        else:
            flat_list.append(item)
    return flat_list

nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)
print("Flattened list:", result)

Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:

In [ ]:
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
    lst (list): A nested list containing numerical elements and/or other lists.

    Returns:
    float: The average of all numerical elements in the nested list.
    """
    def flatten(lst):
        """Helper function to flatten a nested list."""
        flat_list = []
        for item in lst:
            if isinstance(item, list):
                flat_list.extend(flatten(item))  # Recursively flatten nested lists
            else:
                flat_list.append(item)
        return flat_list

    flat_numbers = flatten(lst)
    if not flat_numbers:
        raise ValueError("Cannot calculate the average of an empty list.")

    return sum(flat_numbers) / len(flat_numbers)

nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)
print("Average of all elements:", result)

Average of all elements: 3.5


10.1 Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

In [ ]:
import numpy as np

def numpy_array_operations():
    """
    Performs basic vector and matrix operations using NumPy.

    Returns:
    dict: A dictionary containing results of different NumPy operations.
    """
    results = {}

    # 1. Initialize an empty array with size 2x2
    results['empty_array'] = np.empty((2, 2))

    # 2. Initialize an all-ones array with size 4x2
    results['ones_array'] = np.ones((4, 2))

    # 3. Return a new array of given shape and type, filled with a fill value
    results['full_array'] = np.full((3, 3), 7)  # Example fill value: 7

    # 4. Return a new array of zeros with the same shape and type as a given array
    reference_array = np.array([[1, 2, 3], [4, 5, 6]])
    results['zeros_like'] = np.zeros_like(reference_array)

    # 5. Return a new array of ones with the same shape and type as a given array
    results['ones_like'] = np.ones_like(reference_array)

    # 6. Convert an existing list to a NumPy array
    new_list = [1, 2, 3, 4]
    results['numpy_array'] = np.array(new_list)

    return results

# Example usage:
result_dict = numpy_array_operations()
for key, value in result_dict.items():
    print(f"{key}:\n{value}\n")


empty_array:
[[2.78342830e-316 0.00000000e+000]
 [6.66179359e-310 5.30886346e+180]]

ones_array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

full_array:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

zeros_like:
[[0 0 0]
 [0 0 0]]

ones_like:
[[1 1 1]
 [1 1 1]]

numpy_array:
[1 2 3 4]



Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
import numpy as np

def numpy_array_operations():
    """
    Performs basic vector and matrix operations using NumPy.

    Returns:
    dict: A dictionary containing results of different NumPy operations.
    """
    results = {}

    # 1. Initialize an empty array with size 2x2
    results['empty_array'] = np.empty((2, 2))

    # 2. Initialize an all-ones array with size 4x2
    results['ones_array'] = np.ones((4, 2))

    # 3. Return a new array of given shape and type, filled with a fill value
    results['full_array'] = np.full((3, 3), 7)  # Example fill value: 7

    # 4. Return a new array of zeros with the same shape and type as a given array
    reference_array = np.array([[1, 2, 3], [4, 5, 6]])
    results['zeros_like'] = np.zeros_like(reference_array)

    # 5. Return a new array of ones with the same shape and type as a given array
    results['ones_like'] = np.ones_like(reference_array)

    # 6. Convert an existing list to a NumPy array
    new_list = [1, 2, 3, 4]
    results['numpy_array'] = np.array(new_list)

    # 7. Create an array with values ranging from 10 to 49
    results['range_array'] = np.arange(10, 50)

    # 8. Create a 3x3 matrix with values ranging from 0 to 8
    results['reshaped_matrix'] = np.arange(9).reshape((3, 3))

    # 9. Create a 3x3 identity matrix
    results['identity_matrix'] = np.eye(3)

    # 10. Create a random array of size 30 and find the mean
    random_array = np.random.random(30)
    results['random_array'] = random_array
    results['random_mean'] = random_array.mean()

    # 11. Create a 10x10 array with random values and find min and max
    random_matrix = np.random.random((10, 10))
    results['random_matrix'] = random_matrix
    results['random_min'] = random_matrix.min()
    results['random_max'] = random_matrix.max()

    # 12. Create a zero array of size 10 and replace the 5th element with 1
    zero_array = np.zeros(10)
    zero_array[4] = 1  # Indexing starts at 0
    results['zero_array_modified'] = zero_array

    # 13. Reverse an array
    arr = np.array([1, 2, 0, 0, 4, 0])
    results['reversed_array'] = arr[::-1]

    # 14. Create a 2D array with 1 on the border and 0 inside
    border_array = np.ones((5, 5))
    border_array[1:-1, 1:-1] = 0
    results['border_array'] = border_array

    # 15. Create an 8x8 matrix and fill it with a checkerboard pattern
    checkerboard = np.zeros((8, 8), dtype=int)
    checkerboard[1::2, ::2] = 1
    checkerboard[::2, 1::2] = 1
    results['checkerboard'] = checkerboard

    return results

# Example usage:
result_dict = numpy_array_operations()
for key, value in result_dict.items():
    print(f"{key}:\n{value}\n")

empty_array:
[[2.78342830e-316 0.00000000e+000]
 [6.66179359e-310 5.30886346e+180]]

ones_array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

full_array:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

zeros_like:
[[0 0 0]
 [0 0 0]]

ones_like:
[[1 1 1]
 [1 1 1]]

numpy_array:
[1 2 3 4]

range_array:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

reshaped_matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

identity_matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

random_array:
[0.94727481 0.42567945 0.56129441 0.63284085 0.88359556 0.41134143
 0.24905511 0.53968126 0.8695703  0.2012943  0.93175055 0.54756038
 0.30444134 0.80194092 0.92414509 0.38296655 0.12986249 0.50853516
 0.7790511  0.92949501 0.51492036 0.89895358 0.29944676 0.7447268
 0.93854909 0.95280439 0.79311242 0.4843833  0.87307569 0.58967335]

random_mean:
0.6350340600345556

random_matrix:
[[0.50771894 0.20516026 0.84101919 0.46778971 0.33837013 0.14001556
  0.51399394 0.4579082  0.0822547

Problem - 3: Array Operations:

In [ ]:
import numpy as np

def numpy_array_operations():
    """
    Performs basic vector and matrix operations using NumPy.

    Returns:
    dict: A dictionary containing results of different NumPy operations.
    """
    results = {}

    # 1. Initialize an empty array with size 2x2
    results['empty_array'] = np.empty((2, 2))

    # 2. Initialize an all-ones array with size 4x2
    results['ones_array'] = np.ones((4, 2))

    # 3. Return a new array of given shape and type, filled with a fill value
    results['full_array'] = np.full((3, 3), 7)  # Example fill value: 7

    # 4. Return a new array of zeros with the same shape and type as a given array
    reference_array = np.array([[1, 2, 3], [4, 5, 6]])
    results['zeros_like'] = np.zeros_like(reference_array)

    # 5. Return a new array of ones with the same shape and type as a given array
    results['ones_like'] = np.ones_like(reference_array)

    # 6. Convert an existing list to a NumPy array
    new_list = [1, 2, 3, 4]
    results['numpy_array'] = np.array(new_list)

    # 7. Create an array with values ranging from 10 to 49
    results['range_array'] = np.arange(10, 50)

    # 8. Create a 3x3 matrix with values ranging from 0 to 8
    results['reshaped_matrix'] = np.arange(9).reshape((3, 3))

    # 9. Create a 3x3 identity matrix
    results['identity_matrix'] = np.eye(3)

    # 10. Create a random array of size 30 and find the mean
    random_array = np.random.random(30)
    results['random_array'] = random_array
    results['random_mean'] = random_array.mean()

    # 11. Create a 10x10 array with random values and find min and max
    random_matrix = np.random.random((10, 10))
    results['random_matrix'] = random_matrix
    results['random_min'] = random_matrix.min()
    results['random_max'] = random_matrix.max()

    # 12. Create a zero array of size 10 and replace the 5th element with 1
    zero_array = np.zeros(10)
    zero_array[4] = 1  # Indexing starts at 0
    results['zero_array_modified'] = zero_array

    # 13. Reverse an array
    arr = np.array([1, 2, 0, 0, 4, 0])
    results['reversed_array'] = arr[::-1]

    # 14. Create a 2D array with 1 on the border and 0 inside
    border_array = np.ones((5, 5))
    border_array[1:-1, 1:-1] = 0
    results['border_array'] = border_array

    # 15. Create an 8x8 matrix and fill it with a checkerboard pattern
    checkerboard = np.zeros((8, 8), dtype=int)
    checkerboard[1::2, ::2] = 1
    checkerboard[::2, 1::2] = 1
    results['checkerboard'] = checkerboard

    # 16. Define arrays for operations
    x = np.array([[1, 2], [3, 5]])
    y = np.array([[5, 6], [7, 8]])
    v = np.array([9, 10])
    w = np.array([11, 12])

    # 17. Perform array operations
    results['array_addition'] = x + y
    results['array_subtraction'] = x - y
    results['array_multiplication'] = x * 2  # Multiplying by an integer
    results['array_square'] = x ** 2  # Squaring elements

    # 18. Compute dot products
    results['dot_product_vw'] = np.dot(v, w)
    results['dot_product_xv'] = np.dot(x, v)
    results['dot_product_xy'] = np.dot(x, y)

    # 19. Concatenate x and y along rows
    results['concat_xy'] = np.concatenate((x, y), axis=0)

    # 20. Concatenate v and w along columns
    results['concat_vw'] = np.vstack((v, w))

    # 21. Attempt to concatenate x and v (observe the error)
    try:
        results['concat_xv'] = np.concatenate((x, v), axis=0)
    except ValueError as e:
        results['concat_xv_error'] = str(e)

    return results

# Example usage:
result_dict = numpy_array_operations()
for key, value in result_dict.items():
    print(f"{key}:\n{value}\n")


empty_array:
[[2.85648608e-316 0.00000000e+000]
 [2.86840917e-316 6.66179369e-310]]

ones_array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

full_array:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

zeros_like:
[[0 0 0]
 [0 0 0]]

ones_like:
[[1 1 1]
 [1 1 1]]

numpy_array:
[1 2 3 4]

range_array:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

reshaped_matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

identity_matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

random_array:
[9.97408664e-01 1.13815209e-01 4.44754319e-01 9.49223367e-01
 9.96719886e-01 7.99362818e-01 1.29421979e-01 4.10919477e-01
 4.95780789e-01 6.02652212e-01 4.63089426e-01 5.57694972e-01
 5.96843400e-01 8.73675995e-04 2.55334011e-01 8.44461345e-01
 2.77977717e-01 6.30530794e-01 2.36214469e-01 7.89704378e-01
 9.79260969e-01 2.84266087e-01 7.54115894e-01 5.69747554e-01
 6.56828655e-01 9.52190459e-01 2.57083467e-01 8.71822624e-02
 3.54979289e-01 7.62624183e-01]

random_mean:
0.5417020575

Problem - 4: Matrix Operations:

In [ ]:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A⁻¹ = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A⁻¹ = I:")
print(identity_matrix)

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
is_commutative = np.array_equal(AB, BA)
print("\nAB:")
print(AB)
print("\nBA:")
print(BA)
print("\nAB == BA:", is_commutative)

# 3. Prove (AB)ᵀ = BᵀAᵀ
AB_transpose = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
is_transpose_property_valid = np.array_equal(AB_transpose, BT_AT)
print("\n(AB)ᵀ:")
print(AB_transpose)
print("\nBᵀ Aᵀ:")
print(BT_AT)
print("\n(AB)ᵀ == Bᵀ Aᵀ:", is_transpose_property_valid)

# Solve the system of linear equations using inverse method
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Represent as AX = B
A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_matrix = np.array([-1, -3, 9])

# Solve for X using inverse
A_inverse = np.linalg.inv(A_matrix)
X_solution = np.dot(A_inverse, B_matrix)
print("\nSolution to the system of linear equations (AX = B):")
print(X_solution)


A * A⁻¹ = I:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]

AB == BA: False

(AB)ᵀ:
[[23 51]
 [13 29]]

Bᵀ Aᵀ:
[[23 51]
 [13 29]]

(AB)ᵀ == Bᵀ Aᵀ: True

Solution to the system of linear equations (AX = B):
[ 2.  1. -2.]
